name: Coveralls

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: server/package-lock.json

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '6.0'

    - name: Set environment variables
      run: echo "ATLAS_URI=${{ secrets.ATLAS_URI }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm ci
      working-directory: server

    - name: Run tests and generate coverage
      run: npm run coverage
      working-directory: server
      env:
        ATLAS_URI: ${{ secrets.ATLAS_URI }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    - name: Upload coverage to Coveralls
      if: ${{ success() }}
      run: npx coveralls < coverage/lcov.info
      working-directory: server
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

