name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        node-version: [16.x, 18.x, 19.x, 20.x, 21.x]
        mongodb-version: ['8.0.3']

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json  # Indicamos la ubicación del archivo

    - name: Install dependencies
      working-directory: server
      run: npm install

    - name: Running tests
      working-directory: server
      run: npm run test
